// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRSTV_ConsoleApp.Data;

#nullable disable

namespace PRSTV_ConsoleApp.Migrations
{
    [DbContext(typeof(CountContext))]
    [Migration("20260129191841_AddElection")]
    partial class AddElection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PRSTV_ClassLibrary.CountClasses.Election", b =>
                {
                    b.Property<int>("ElectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ElectionId"));

                    b.Property<int>("CurrentCount")
                        .HasColumnType("int");

                    b.Property<int>("Quota")
                        .HasColumnType("int");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<int>("SeatsFilled")
                        .HasColumnType("int");

                    b.Property<int>("TotalValidPoll")
                        .HasColumnType("int");

                    b.HasKey("ElectionId");

                    b.HasIndex("CurrentCount");

                    b.ToTable("Elections", (string)null);
                });

            modelBuilder.Entity("PRSTV_ConsoleApp.BallotCurrentState", b =>
                {
                    b.Property<int>("BallotCurrentStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BallotCurrentStateId"));

                    b.Property<int>("CountNumber")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentCandidateId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentPreference")
                        .HasColumnType("int");

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsExhausted")
                        .HasColumnType("bit");

                    b.Property<int>("LatestCountTransfered")
                        .HasColumnType("int");

                    b.Property<long>("RandomBallotId")
                        .HasColumnType("bigint");

                    b.HasKey("BallotCurrentStateId");

                    b.HasIndex("ElectionId");

                    b.HasIndex("RandomBallotId");

                    b.HasIndex("CountNumber", "CurrentCandidateId");

                    b.HasIndex("CountNumber", "RandomBallotId");

                    b.HasIndex("CountNumber", "CurrentCandidateId", "IsExhausted");

                    b.ToTable("BallotCurrentStates", (string)null);
                });

            modelBuilder.Entity("PRSTV_ConsoleApp.LocalDB.CandidateCountState", b =>
                {
                    b.Property<int>("CandidateCountStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CandidateCountStateId"));

                    b.Property<int?>("BallotsTransferredAmount")
                        .HasColumnType("int");

                    b.Property<long>("CandidateId")
                        .HasColumnType("bigint");

                    b.Property<int>("CountNumber")
                        .HasColumnType("int");

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Surplus")
                        .HasColumnType("int");

                    b.Property<int>("TotalVotes")
                        .HasColumnType("int");

                    b.HasKey("CandidateCountStateId");

                    b.HasIndex("ElectionId");

                    b.HasIndex("CountNumber", "CandidateId");

                    b.HasIndex("CountNumber", "Status");

                    b.ToTable("CandidateCountStates", (string)null);
                });

            modelBuilder.Entity("PRSTV_ConsoleApp.BallotCurrentState", b =>
                {
                    b.HasOne("PRSTV_ClassLibrary.CountClasses.Election", "Election")
                        .WithMany("BallotStates")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Election");
                });

            modelBuilder.Entity("PRSTV_ConsoleApp.LocalDB.CandidateCountState", b =>
                {
                    b.HasOne("PRSTV_ClassLibrary.CountClasses.Election", "Election")
                        .WithMany("CandidateStates")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Election");
                });

            modelBuilder.Entity("PRSTV_ClassLibrary.CountClasses.Election", b =>
                {
                    b.Navigation("BallotStates");

                    b.Navigation("CandidateStates");
                });
#pragma warning restore 612, 618
        }
    }
}
